//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package me.zimity.android.app;

import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import me.zimity.android.app.R.id;
import me.zimity.android.app.R.layout;

public final class ImprintMenu_
    extends ImprintMenu
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        beforeCreate_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.imprint);
        afterSetContentView_(savedInstanceState);
    }

    private void beforeCreate_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_(Bundle savedInstanceState) {
        findViewById(id.event).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                eventActivity(view);
            }

        }
        );
        findViewById(id.audio_button).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                audioActivity(view);
            }

        }
        );
        findViewById(id.reminder).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                reminderActivity(view);
            }

        }
        );
        findViewById(id.caption_button).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                captionActivity(view);
            }

        }
        );
        findViewById(id.photo).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                photoActivity(view);
            }

        }
        );
        findViewById(id.video).setOnClickListener(new OnClickListener() {


            public void onClick(View view) {
                videoActivity(view);
            }

        }
        );
        init();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

}
